services:
  mongo:
    image: mongo
    volumes:
      - mdata:/etc/data
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

  app:
    build: .
    volumes:
      - ./shopping_list:/home/app/shopping_list
      - ./src:/home/app/src
      - ./test:/home/app/test
      - ./output:/home/app/output
    env_file:
      - .env
    depends_on:
      - mongo
    tty: true

volumes:
  mdata:
